**Contributors:**
Vivek Khimani and Jongyi

**Description:**
Based on aspects of building location and construction, the goal is to predict the level of damage to buildings caused by the 2015 Gorkha earthquake in Nepal.

**Data Credits:**
Central Bureau of Statistics that work under the National Planning Commission Secretariat of Nepal.

**Occassion:**
DrivenData Practice Competition

In [2]:
#Import Statements
 !python3 -m io
import pandas as pd
import numpy as np
import csv
from google.colab import files
import seaborn as sns


from sklearn.metrics import accuracy_score,classification_report,log_loss,confusion_matrix,roc_curve,auc
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder,MinMaxScaler,LabelEncoder
import matplotlib.pyplot as plt
from matplotlib.legend_handler import HandlerLine2D
from imblearn.over_sampling import SMOTE
import io

from sklearn.neural_network import MLPClassifier



/usr/local/lib/python3.6/dist-packages/sklearn/externals/six.py:31: DeprecationWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", DeprecationWarning)


In [0]:
#Importing data from raw github files
train_values_url = 'https://raw.githubusercontent.com/vivekkhimani/RitcherEarthquakeDamagePredictor/master/data/train_values.csv'
train_labels_url = 'https://raw.githubusercontent.com/vivekkhimani/RitcherEarthquakeDamagePredictor/master/data/train_labels.csv'
submission_data_url = 'https://raw.githubusercontent.com/vivekkhimani/RitcherEarthquakeDamagePredictor/master/data/test_values.csv'

#Converting the raw imported data to pandas dataframes
train_values = pd.read_csv(train_values_url)
train_labels = pd.read_csv(train_labels_url)
submission_values = pd.read_csv(submission_data_url)

#Label Encoding
label_encoder = LabelEncoder()
train_values = train_values.apply(label_encoder.fit_transform)

#Convering the TRAINING dataframes to arrays
data_X = train_values.iloc[:,1:].to_numpy()
data_Y = train_labels.iloc[:,1].to_numpy()



In [10]:
#One Hot Encoding
ohe = OneHotEncoder(categorical_features = [7,8,9,10,11,12,13,25])
data_X = ohe.fit_transform(data_X).toarray()


#Splitting Train and Test sets from the given training data
X_train,Y_train,X_test,Y_test = train_test_split(data_X, data_Y, test_size = 0.33, random_state = 42)


#checking for class imbalance
counter1 = 0
counter2 = 0
counter3 = 0

for items in data_Y:
  if items == 1:
    counter1+=1
  if items == 2:
    counter2+=1
  if items == 3:
    counter3+=1
    
    
print(counter1,counter2,counter3)
print(X_train.shape)
print(X_train)
#print(Y_train.shape)
#print(X_test.shape)
#print(Y_test.shape)
#sns.distplot(data_Y)

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


25124 148259 87218
(174602, 68)
[[0. 0. 1. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]]


In [0]:
#Vivek Block
#GridSeachCV and Randomized Search
#Get the parameters, run the model, and check the metrics

In [0]:
#Jongyi Block
#Overfitting and Underfitting Metrics
#Plotting AUC ROC curve